{
  "headers": {
    
  },
  "attachments": {
    
  },
  "body": {
    "getRecordsResponse": {
      "getRecordsResult": {
        "active": "0",
        "activity_due": null,
        "additional_assignee_list": null,
        "approval": "not requested",
        "approval_set": null,
        "assigned_to": null,
        "assignment_group": null,
        "business_duration": "1970-01-02 00:00:00",
        "business_service": null,
        "business_stc": "86400",
        "calendar_duration": "1970-01-04 01:26:57",
        "calendar_stc": "264417",
        "caller_id": "46d44a23a9fe19810012d100cca80666",
        "category": "hardware",
        "caused_by": null,
        "child_incidents": "0",
        "close_code": "Solved (Work Around)",
        "close_notes": "As this is intermittent. Restarting the PC fixes this.",
        "closed_at": "2021-10-19 13:39:42",
        "closed_by": "62d78687c0a8010e00b3d84178adc913",
        "cmdb_ci": "affd3c8437201000deeabfc8bcbe5dc3",
        "comments_and_work_notes": null,
        "company": "31bea3d53790200044e0bfc8bcbe5dec",
        "contact_type": "walk-in",
        "contract": null,
        "correlation_display": null,
        "correlation_id": null,
        "delivery_plan": null,
        "delivery_task": null,
        "description": null,
        "due_date": null,
        "escalation": "0",
        "expected_start": null,
        "follow_up": null,
        "group_list": null,
        "hold_reason": "0",
        "impact": "3",
        "incident_state": "7",
        "knowledge": "0",
        "location": null,
        "made_sla": "1",
        "notify": "1",
        "number": "INC0000601",
        "opened_at": "2021-02-24 09:42:59",
        "opened_by": "6816f79cc0a8016401c5a33be04be441",
        "order": "0",
        "parent": null,
        "parent_incident": null,
        "priority": "5",
        "problem_id": "8f74a828532023004247ddeeff7b1295",
        "reassignment_count": "0",
        "reopen_count": "0",
        "reopened_by": null,
        "reopened_time": null,
        "resolved_at": "2021-02-27 11:09:56",
        "resolved_by": "62d78687c0a8010e00b3d84178adc913",
        "rfc": null,
        "route_reason": "0",
        "service_offering": null,
        "severity": "3",
        "short_description": "The USB port on my PC stopped working",
        "sla_due": null,
        "state": "7",
        "subcategory": null,
        "sys_class_name": "incident",
        "sys_created_by": "admin",
        "sys_created_on": "2021-02-24 09:43:10",
        "sys_domain": "global",
        "sys_domain_path": "/",
        "sys_id": "9e7f9864532023004247ddeeff7b121f",
        "sys_mod_count": "2",
        "sys_updated_by": "system",
        "sys_updated_on": "2021-10-19 13:39:42",
        "task_effective_number": "INC0000601",
        "time_worked": null,
        "universal_request": null,
        "upon_approval": "proceed",
        "upon_reject": "cancel",
        "urgency": "3",
        "user_input": null,
        "watch_list": null,
        "work_end": null,
        "work_notes_list": null,
        "work_start": null
      },
      "getRecordsResult": {
        "active": "1",
        "activity_due": null,
        "additional_assignee_list": null,
        "approval": "not requested",
        "approval_set": null,
        "assigned_to": null,
        "assignment_group": null,
        "business_duration": null,
        "business_service": null,
        "business_stc": "0",
        "calendar_duration": null,
        "calendar_stc": "0",
        "caller_id": "6816f79cc0a8016401c5a33be04be441",
        "category": "inquiry",
        "caused_by": null,
        "child_incidents": "0",
        "close_code": null,
        "close_notes": null,
        "closed_at": null,
        "closed_by": null,
        "cmdb_ci": null,
        "comments_and_work_notes": null,
        "company": null,
        "contact_type": null,
        "contract": null,
        "correlation_display": null,
        "correlation_id": null,
        "delivery_plan": null,
        "delivery_task": null,
        "description": null,
        "due_date": null,
        "escalation": "0",
        "expected_start": null,
        "follow_up": null,
        "group_list": null,
        "hold_reason": "0",
        "impact": "3",
        "incident_state": "1",
        "knowledge": "0",
        "location": null,
        "made_sla": "1",
        "notify": "1",
        "number": "INC0010111",
        "opened_at": "2019-07-22 21:04:57",
        "opened_by": "6816f79cc0a8016401c5a33be04be441",
        "order": "0",
        "parent": null,
        "parent_incident": null,
        "priority": "5",
        "problem_id": null,
        "reassignment_count": "0",
        "reopen_count": "0",
        "reopened_by": null,
        "reopened_time": null,
        "resolved_at": null,
        "resolved_by": null,
        "rfc": null,
        "route_reason": "0",
        "service_offering": null,
        "severity": "3",
        "short_description": "ATF : Test1",
        "sla_due": null,
        "state": "1",
        "subcategory": null,
        "sys_class_name": "incident",
        "sys_created_by": "admin",
        "sys_created_on": "2019-07-22 21:05:17",
        "sys_domain": "global",
        "sys_domain_path": "/",
        "sys_id": "a83820b58f723300e7e16c7827bdeed2",
        "sys_mod_count": "1",
        "sys_updated_by": "admin",
        "sys_updated_on": "2019-07-22 21:05:48",
        "task_effective_number": "INC0010111",
        "time_worked": null,
        "universal_request": null,
        "upon_approval": "proceed",
        "upon_reject": "cancel",
        "urgency": "3",
        "user_input": null,
        "watch_list": null,
        "work_end": null,
        "work_notes_list": null,
        "work_start": null
      },
      "getRecordsResult": {
        "active": "1",
        "activity_due": null,
        "additional_assignee_list": null,
        "approval": "not requested",
        "approval_set": null,
        "assigned_to": null,
        "assignment_group": null,
        "business_duration": null,
        "business_service": null,
        "business_stc": "0",
        "calendar_duration": null,
        "calendar_stc": "0",
        "caller_id": "005d500b536073005e0addeeff7b12f4",
        "category": "inquiry",
        "caused_by": null,
        "child_incidents": "0",
        "close_code": null,
        "close_notes": null,
        "closed_at": null,
        "closed_by": null,
        "cmdb_ci": null,
        "comments_and_work_notes": null,
        "company": null,
        "contact_type": null,
        "contract": null,
        "correlation_display": null,
        "correlation_id": null,
        "delivery_plan": null,
        "delivery_task": null,
        "description": null,
        "due_date": null,
        "escalation": "0",
        "expected_start": null,
        "follow_up": null,
        "group_list": null,
        "hold_reason": "0",
        "impact": "3",
        "incident_state": "1",
        "knowledge": "0",
        "location": null,
        "made_sla": "1",
        "notify": "1",
        "number": "INC0010112",
        "opened_at": "2019-07-29 18:48:43",
        "opened_by": "6816f79cc0a8016401c5a33be04be441",
        "order": "0",
        "parent": null,
        "parent_incident": null,
        "priority": "5",
        "problem_id": null,
        "reassignment_count": "0",
        "reopen_count": "0",
        "reopened_by": null,
        "reopened_time": null,
        "resolved_at": null,
        "resolved_by": null,
        "rfc": null,
        "route_reason": "0",
        "service_offering": null,
        "severity": "3",
        "short_description": "Assessment :  ATF Assessor",
        "sla_due": null,
        "state": "1",
        "subcategory": null,
        "sys_class_name": "incident",
        "sys_created_by": "admin",
        "sys_created_on": "2019-07-29 18:49:28",
        "sys_domain": "global",
        "sys_domain_path": "/",
        "sys_id": "552c48888c033300964f4932b03eb092",
        "sys_mod_count": "0",
        "sys_updated_by": "admin",
        "sys_updated_on": "2019-07-29 18:49:28",
        "task_effective_number": "INC0010112",
        "time_worked": null,
        "universal_request": null,
        "upon_approval": "proceed",
        "upon_reject": "cancel",
        "urgency": "3",
        "user_input": null,
        "watch_list": null,
        "work_end": null,
        "work_notes_list": null,
        "work_start": null
      }
    }
  }
}